//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class geolocations
    {
        public int id { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string ip { get; set; }
        public string ipType { get; set; }
        public string continentCode { get; set; }
        public string continentName { get; set; }
        public string countryCode { get; set; }
        public string regionCode { get; set; }
        public string regionName { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
    }
}
